### ISSUE TITLE
Plugin doesn't properly loaded

### ISSUE THREAD

**Issue by resilva** [du-song/SublimeFormatSQL#1]
Hi,

i've an error when i try to load your plugin wich is seems awefull, can you try to fix it please ? Here it is the part of log wich is interesting :

OS : Windows 7 (if this can help)

Reloading plugin C:\Users****\AppData\Roaming\Sublime Text 2\Packages\Format SQL\FormatSQL.py
Traceback (most recent call last):
  File ".\sublime_plugin.py", line 59, in reload_plugin
  File ".\FormatSQL.py", line 5, in <module>
    import sqlparse
  File ".\sqlparse__init__.py", line 17, in <module>
    from sqlparse import engine
  File ".\sqlparse\engine__init__.py", line 8, in <module>
    from sqlparse import lexer
  File ".\sqlparse\lexer.py", line 18, in <module>
    from sqlparse.keywords import KEYWORDS, KEYWORDS_COMMON
  File ".\sqlparse\keywords.py", line 4, in <module>
    'ABORT': tokens.Keyword,
AttributeError: 'module' object has no attribute 'Keyword'

Thanks in advance,
Romain

**Comment by du-song** [comment]
Hi,
I never met this issue on Mac, just got a Windows 7 machine to try this out.
It works fine with a fresh install of Sublime Text 2 (latest dev build, 32 bit).
I'm going to close this.
Could you give one more try and report again if it's really an issue with this plugin?
//btw, pull request welcomed!
