### ISSUE TITLE
selection 》 Format 》Format SQL Statement is disabled？

### ISSUE THREAD

**Issue by kntao** [du-song/SublimeFormatSQL#16]
on windows platform， why ”Format SQL Statement“ button is disabled？

**Comment by grantmcconnaughey** [comment]
Same for Mac OS X 10.9.1, Sublime Text 2.

**Comment by bsiamionau** [comment]
Windows 7, Sublime 2.0.2, same thing

**Comment by jonwhittlestone** [comment]
Same for Mac OS X 10.9.1, ST3

**Comment by DBD80** [comment]
Got same the same issue on Win 7, Sublime Text 2, v 2.0.2, Build: 2221

**Comment by bani** [comment]
In case anyone is interested, I created a fork that works with Sublime 2:
https://github.com/bani/SublimeFormatSQL
If you are using the package manager you can add this repository.

**Comment by iies** [comment]
Me too, Mac OSX 10.9.1 / ST2.0.2
but bani's repository is worked! thanks bani.

**Comment by adworacz** [comment]
How do you install Bani's version using the package manager?

**Comment by osscca** [comment]
@bani Your fork works perfect in ST2! When will ST3 be supported?

@adworacz This is explained on the Package Control website: https://sublime.wbond.net/docs/usage

**Comment by bani** [comment]
@osscca Apparently supporting both versions is tricky. I don't use ST3, so it's not in my plans.
The last work done for ST3 support seems to be https://github.com/freewizard/SublimeFormatSQL/pull/12 by @kgantsov

**Comment by osscca** [comment]
Thanks @bani. I've done some additional testing and apparently this version works correct in ST3 on Windows, but not on OS X.

**Comment by rstackhouse** [comment]
Got same the same issue on OS X Maviercks, Sublime Text 2, v 2.0.2, Build: 2221

**Comment by travelliu** [comment]
mac os 10.9.3 sublime 3
Traceback (most recent call last):
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 73, in reload_plugin
    m = importlib.import_module(modulename)
  File "X/importlib/**init**.py", line 88, in import_module
  File "<frozen importlib._bootstrap>", line 1577, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1558, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1525, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 586, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1023, in load_module
  File "<frozen importlib._bootstrap>", line 1004, in load_module
  File "<frozen importlib._bootstrap>", line 562, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 869, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/SublimeFormatSQL/FormatSQL.py", line 6, in <module>
    from .sqlparse import format
  File "/Users/Travel/Library/Application Support/Sublime Text 3/Packages/SublimeFormatSQL/sqlparse/__init__.py", line 13, in <module>
    from sqlparse import engine
ImportError: No module named 'sqlparse'
plugins loaded

**Comment by adworacz** [comment]
Read the README for this project. It specifically says to have the python sqlparse library installed. This will fix your issue.

**Comment by dialex** [comment]
Don't even worry and **switch to [SQLBeautifier](https://sublime.wbond.net/packages/SqlBeautifier)**. Works for ST2/3 and doesn't force you to install python. Cheers ;)

**Comment by rstackhouse** [comment]
@dialex [The docs](https://sublime.wbond.net/packages/SqlBeautifier) disagree with you. 

<blockquote>
This is a SQL formatter plugin using python-sqlparse for both Sublime 2 and 3.
</blockquote>

I have had much better luck with SQLBeautifier though. sqlparse is just a <code>pip install python</code> away though.

**Comment by taeseong** [comment]
@bani thank you very much!

**Comment by manyata** [comment]
@bani seems to crash on ST2 .. if i press Command+S twice on a selection.

**Comment by icalderond** [comment]
Thanks @bani plugging work very well.
