### ISSUE TITLE
Corrupted install package on Ubuntu 11.10

### ISSUE THREAD

**Issue by scomp** [du-song/SublimeFormatSQL#3]
The package manager kicks out this error( even though on  screen it says successful install)

Exception in thread Thread-5:
Traceback (most recent call last):
  File ".\threading.py", line 532, in **bootstrap_inner
  File "./Package Control.py", line 1680, in run
  File "./Package Control.py", line 1188, in install_package
  File ".\zipfile.py", line 696, in __init**
  File ".\zipfile.py", line 716, in _GetContents
  File ".\zipfile.py", line 728, in _RealGetContents
BadZipfile: File is not a zip file

**Comment by du-song** [comment]
Hi, 
Zip was compressed by Github automatically
I tried a fresh install which works fine. 
Could you give one more try?
